//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyCAP.EnergyCapSvcRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Building", Namespace="http://schemas.datacontract.org/2004/07/EnergyCAPService")]
    [System.SerializableAttribute()]
    public partial class Building : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuildingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingCode {
            get {
                return this.BuildingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingCodeField, value) != true)) {
                    this.BuildingCodeField = value;
                    this.RaisePropertyChanged("BuildingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuildingID {
            get {
                return this.BuildingIDField;
            }
            set {
                if ((this.BuildingIDField.Equals(value) != true)) {
                    this.BuildingIDField = value;
                    this.RaisePropertyChanged("BuildingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingMemo {
            get {
                return this.BuildingMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingMemoField, value) != true)) {
                    this.BuildingMemoField = value;
                    this.RaisePropertyChanged("BuildingMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Meter", Namespace="http://schemas.datacontract.org/2004/07/EnergyCAPService")]
    [System.SerializableAttribute()]
    public partial class Meter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MeterInfoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterSerialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterCode {
            get {
                return this.MeterCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterCodeField, value) != true)) {
                    this.MeterCodeField = value;
                    this.RaisePropertyChanged("MeterCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MeterInfoID {
            get {
                return this.MeterInfoIDField;
            }
            set {
                if ((this.MeterInfoIDField.Equals(value) != true)) {
                    this.MeterInfoIDField = value;
                    this.RaisePropertyChanged("MeterInfoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterName {
            get {
                return this.MeterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNameField, value) != true)) {
                    this.MeterNameField = value;
                    this.RaisePropertyChanged("MeterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterSerial {
            get {
                return this.MeterSerialField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterSerialField, value) != true)) {
                    this.MeterSerialField = value;
                    this.RaisePropertyChanged("MeterSerial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bill", Namespace="http://schemas.datacontract.org/2004/07/EnergyCAPService")]
    [System.SerializableAttribute()]
    public partial class Bill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillMtrIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterADemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterBDemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterUseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillMtrID {
            get {
                return this.BillMtrIDField;
            }
            set {
                if ((this.BillMtrIDField.Equals(value) != true)) {
                    this.BillMtrIDField = value;
                    this.RaisePropertyChanged("BillMtrID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterADem {
            get {
                return this.MeterADemField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterADemField, value) != true)) {
                    this.MeterADemField = value;
                    this.RaisePropertyChanged("MeterADem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterBDem {
            get {
                return this.MeterBDemField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterBDemField, value) != true)) {
                    this.MeterBDemField = value;
                    this.RaisePropertyChanged("MeterBDem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterCost {
            get {
                return this.MeterCostField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterCostField, value) != true)) {
                    this.MeterCostField = value;
                    this.RaisePropertyChanged("MeterCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterEndDate {
            get {
                return this.MeterEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterEndDateField, value) != true)) {
                    this.MeterEndDateField = value;
                    this.RaisePropertyChanged("MeterEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterStartDate {
            get {
                return this.MeterStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterStartDateField, value) != true)) {
                    this.MeterStartDateField = value;
                    this.RaisePropertyChanged("MeterStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterUse {
            get {
                return this.MeterUseField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterUseField, value) != true)) {
                    this.MeterUseField = value;
                    this.RaisePropertyChanged("MeterUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportMonth {
            get {
                return this.ReportMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportMonthField, value) != true)) {
                    this.ReportMonthField = value;
                    this.RaisePropertyChanged("ReportMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportYear {
            get {
                return this.ReportYearField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportYearField, value) != true)) {
                    this.ReportYearField = value;
                    this.RaisePropertyChanged("ReportYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnergyCapSvcRef.IEnergyCapService")]
    public interface IEnergyCapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnergyCapService/GetData", ReplyAction="http://tempuri.org/IEnergyCapService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnergyCapService/GetBuildings", ReplyAction="http://tempuri.org/IEnergyCapService/GetBuildingsResponse")]
        EnergyCAP.EnergyCapSvcRef.Building[] GetBuildings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnergyCapService/GetMetersForBuilding", ReplyAction="http://tempuri.org/IEnergyCapService/GetMetersForBuildingResponse")]
        EnergyCAP.EnergyCapSvcRef.Meter[] GetMetersForBuilding(int buildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnergyCapService/GetBillsForMeter", ReplyAction="http://tempuri.org/IEnergyCapService/GetBillsForMeterResponse")]
        EnergyCAP.EnergyCapSvcRef.Bill[] GetBillsForMeter(int meterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnergyCapService/GetBuildingDetails", ReplyAction="http://tempuri.org/IEnergyCapService/GetBuildingDetailsResponse")]
        EnergyCAP.EnergyCapSvcRef.Building GetBuildingDetails(int buildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnergyCapService/GetBuildingName", ReplyAction="http://tempuri.org/IEnergyCapService/GetBuildingNameResponse")]
        string GetBuildingName(int buildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnergyCapService/GetMeterName", ReplyAction="http://tempuri.org/IEnergyCapService/GetMeterNameResponse")]
        string GetMeterName(int meterInfoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnergyCapService/UpdateBuildingDetails", ReplyAction="http://tempuri.org/IEnergyCapService/UpdateBuildingDetailsResponse")]
        int UpdateBuildingDetails(EnergyCAP.EnergyCapSvcRef.Building building);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnergyCapServiceChannel : EnergyCAP.EnergyCapSvcRef.IEnergyCapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnergyCapServiceClient : System.ServiceModel.ClientBase<EnergyCAP.EnergyCapSvcRef.IEnergyCapService>, EnergyCAP.EnergyCapSvcRef.IEnergyCapService {
        
        public EnergyCapServiceClient() {
        }
        
        public EnergyCapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnergyCapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnergyCapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnergyCapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public EnergyCAP.EnergyCapSvcRef.Building[] GetBuildings() {
            return base.Channel.GetBuildings();
        }
        
        public EnergyCAP.EnergyCapSvcRef.Meter[] GetMetersForBuilding(int buildingID) {
            return base.Channel.GetMetersForBuilding(buildingID);
        }
        
        public EnergyCAP.EnergyCapSvcRef.Bill[] GetBillsForMeter(int meterID) {
            return base.Channel.GetBillsForMeter(meterID);
        }
        
        public EnergyCAP.EnergyCapSvcRef.Building GetBuildingDetails(int buildingID) {
            return base.Channel.GetBuildingDetails(buildingID);
        }
        
        public string GetBuildingName(int buildingID) {
            return base.Channel.GetBuildingName(buildingID);
        }
        
        public string GetMeterName(int meterInfoID) {
            return base.Channel.GetMeterName(meterInfoID);
        }
        
        public int UpdateBuildingDetails(EnergyCAP.EnergyCapSvcRef.Building building) {
            return base.Channel.UpdateBuildingDetails(building);
        }
    }
}
